export const helpCards = [
    {
      title: "Anumaan",
      subtitle: "What is",
      highlight: "Anumaan?",
      additionalText: ".",
      bgColor: "bg-purple-600",
      highlightBgColor: "bg-purple-800",
      textColor: "text-white"
    },
    {
      title: "Anumaan",
      subtitle: "How to",
      highlight: "Trade on",
      additionalText: "Anumaan?",
      bgColor: "bg-sky-400",
      highlightBgColor: "bg-sky-600",
      textColor: "text-white"
    },
    {
      title: "Anumaan",
      subtitle: "Does Anumaan",
      highlight: "Offer Real",
      additionalText: "Money?",
      bgColor: "bg-pink-200",
      highlightBgColor: "bg-pink-300",
    }
  ];
  
  export const secondRowCards = [
    {
      title: "Anumaan",
      subtitle: "Can We",
      highlight: "Cancel Trades",
      additionalText: "On Anumaan?",
      bgColor: "bg-pink-200",
      highlightBgColor: "bg-pink-300",
    },
    {
      title: "Anumaan",
      subtitle: "How To",
      highlight: "Withdraw",
      additionalText: "Profits?",
      bgColor: "bg-emerald-200",
      highlightBgColor: "bg-emerald-400",
    },
    {
      title: "Anumaan",
      subtitle: "Can i Withdraw",
      highlight: "All Profit",
      additionalText: "In One Day?",
      bgColor: "bg-fuchsia-400",
      highlightBgColor: "bg-fuchsia-600",
      textColor: "text-white"
    }
  ];
  
  export const faqItems = [
    {
      question: "When Will I Get The Payment?",
      answer: "You will get the payments when the events are settled, roughly between 24-48 hours."
    },
    {
      question: "What do I do? I did not get my withdrawal money?",
      answer: "If the withdrawal is sucessful, we will share the UTR number generated by our payment gateway. Alternatively, you can check your updated bank statement to date."
    },
    {
      question: "When Will My Recharge Be Successful?",
      answer: "In case of an issue with recharge, if any payment is pending, the amount gets credited back to the original payment source within 2 to 24 hours."
    },
    {
      question: "Why is my withdrawal getting failed?",
      answer: "All the failed payments will instantly get refunded into your probo wallet. Sometimes the withdrawal fails because of internet connection, power failure, too many transactions processed in one go, and such."
    }
  ];
  
  export const filterButtons = [
    { label: "Top Question", isActive: true },
    { label: "Payments" },
    { label: "Trading" },
    { label: "Kyc" }
  ];